### ISSUE TITLE
VOTE!

### ISSUE THREAD

**Issue by webbrowser11** [Alter-Net-codes/open-source-vote#1]
1: Simple To-Do List App (MIGHT BE MADE FOR SKYOS IF YOU DONT VOTE IT)
   Adding Tasks: Users can add new tasks to their list.
   Viewing Tasks: Display the list of tasks.
   Marking Tasks Complete: Allow users to mark tasks as done and remove them from the list.
   Saving Data: Save the tasks to a file so they persist when the app is closed and reopened.
2: Quiz Game
   Question Bank: A list of questions with multiple-choice answers.
   Random Questions: Select random questions to ask the player.
   Score Keeping: Keep track of the player's score based on correct answers.
   Feedback: Provide feedback on whether the answer was correct or incorrect.
3: Virtual Pet (will be added to SkyOS if it wins)
  Pet Status: Display the pet's status (happiness, hunger, etc.).
   Actions: Allow users to feed, play with, or give the pet rest to change its status.
   Time-Based Changes: Make the pet's status change over time (e.g., it gets hungrier or less happy).
   Graphics: Use simple text graphics or ASCII art to represent the pet.

**Comment by webbrowser11** [comment]
@Scratch_Fakemon com and vote

**Comment by webbrowser11** [comment]
@ScratchFakemon come vote

**Comment by webbrowser11** [comment]
@pikapopcorn @bambus80

**Comment by webbrowser11** [comment]
come vote!

**Comment by webbrowser11** [comment]
@3qtvoyqoieuyot @Katelyn-software
come vote!

**Comment by ScratchFakemon** [comment]
Virtual pet

**Comment by Katelyn-software** [comment]
I vote for Virtual Pet.

**Comment by webbrowser11** [comment]
2 votes for virtual pet!

**Comment by webbrowser11** [comment]
2 votes for virtual pet! 1 vote for simple task manager

**Comment by webbrowser11** [comment]
HELLO vote closes august 2nd so vote fast (yes the one with the most votes tomorrow will begin dev) we still want to see what wins

**Comment by 3qtvoyqoieuyot** [comment]
virtual pet

**Comment by webbrowser11** [comment]
I vote virtual pet

**Comment by webbrowser11** [comment]
4 votes for virtual pet 1 vote for simple task manager

**Comment by Tropics09** [comment]
Task Manager

**Comment by webbrowser11** [comment]
thank you we are closing now.
